### ISSUE TITLE
无法获取textarea中的内容

### ISSUE THREAD

**Issue by zchrissirhcz** [chenjiangsong/vue-codemirror#2]
看到你的代码放在`ready()`中进行编辑区域的初始化。
怎样获取里面的内容呢？因为想把内容提交到服务器，比如R语言的代码，运行后把结果显示在前端界面。

用`<textarea v-el:editor v-model="msg">`获取不到里面的内容，求解

**Comment by zchrissirhcz** [comment]
感觉还是需要用`directive`的写法，双向指令，把数据写回

**Comment by chenjiangsong** [comment]
兄弟你跟得真紧。。很好，这个代码还没写完。。

**Comment by zchrissirhcz** [comment]
嗯，我暂时用了这里的代码：`https://github.com/surmon-china/vue-codemirror`，你也可以作为参考。
